apiVersion: v1
kind: Service
metadata:
  name: compute
  labels:
    app: compute
spec:
  #type: NodePort
  type: LoadBalancer
  #externalIPs:
  #- 192.168.1.120
  ports:
  - port: 8008
    targetPort: 8008
    name: http
  selector:
    app: compute