apiVersion: apps/v1
kind: Deployment
metadata:
  name: store
  labels:
    app: store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store
  template:
    metadata:
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
      labels:
        app: store
    spec:
      containers:
      - name: store
        image: hchetoui/store:1.0
        ports:
        - containerPort: 8010
        env:
        - name: compute
          #value: 10.76.216.52:30148/compute/multiple
          #value: http://192.168.6.3:32159/compute/multiple
          valueFrom:
            configMapKeyRef:
              name: compute
              key: compute-url