apiVersion: v1
kind: Service
metadata:
  name: store
  labels:
    app: store
spec:
  #type: NodePort
  type: LoadBalancer
  ports:
  - port: 8010
    targetPort: 8010
    name: http
  selector:
    app: store